version: "3"
services:
  app:
    stdin_open: true
    tty: true
    build: .
    image: golang:1.14.5-stretch
    container_name: golang-tutorial
    volumes:
      - "/home/kaiba/Code/golang/tutorial/app:/go"
